version: '3.8'

services:
  backend-service:
    image: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile

  frontend-service:
    image: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      - BACKEND_PORT = 8081
      - BACKEND_DNS = backend-service
    depends_on:
      - backend-service

