version: '3.8'

services:
  backend-svc:
    image: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile

  frontend-svc:
    image: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      - BACKEND_PORT=9000
      - BACKEND_DNS=backend-svc
    depends_on:
      - backend-svc

