name: Main workflow
on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.12'

      - name: Clone down repository
        uses: actions/checkout@v4   

      - name: Build application and test
        run: |
          cd backend
          go build -buildvcs=false
          cd ../frontend
          go build -buildvcs=false
          go test

