name: Main workflow
on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.12'

      - name: Build application and test
        run: |
          cd backend
          go build -buildvcs=false
          cd ../frontend
          go build -buildvcs=false
          go test

  PushDockerHub:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker images
      run: |
        docker build -t nipel24/backend:latest ./backend 
        docker build -t nipel24/frontend:latest ./frontend

    - name: Push Docker images to DockerHub
      run: |
        docker push nipel24/backend:latest 
        docker push nipel24/frontend:latest