name: Main workflow
on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4      
      - name: Build application
        run: |
          cd backend
          go build 
          cd ../frontend
          go build
          go test

